version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio-escola
    ports:
      - "5432:5432"
